//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHS.DEVICE.WEIGHT.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WHS.DEVICE.WEIGHT.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 称重 的本地化字符串。
        /// </summary>
        internal static string PluginDisplayText {
            get {
                return ResourceManager.GetString("PluginDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能为空 的本地化字符串。
        /// </summary>
        internal static string Validation_Commons_NotEmpty {
            get {
                return ResourceManager.GetString("Validation.Commons.NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请验证COM端口是否被禁用或未连接设备 的本地化字符串。
        /// </summary>
        internal static string WeightView_Bind_ErrorText {
            get {
                return ResourceManager.GetString("WeightView.Bind.ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string WeightView_Btn_Save {
            get {
                return ResourceManager.GetString("WeightView.Btn.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string WeightView_Combobox_Watermark {
            get {
                return ResourceManager.GetString("WeightView.Combobox.Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 称重配置 的本地化字符串。
        /// </summary>
        internal static string WeightView_Content_Title {
            get {
                return ResourceManager.GetString("WeightView.Content.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位/秒: 的本地化字符串。
        /// </summary>
        internal static string WeightView_Label_BitRate {
            get {
                return ResourceManager.GetString("WeightView.Label.BitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 奇偶校验: 的本地化字符串。
        /// </summary>
        internal static string WeightView_Label_CheckBit {
            get {
                return ResourceManager.GetString("WeightView.Label.CheckBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口名称: 的本地化字符串。
        /// </summary>
        internal static string WeightView_Label_COMPort {
            get {
                return ResourceManager.GetString("WeightView.Label.COMPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据位: 的本地化字符串。
        /// </summary>
        internal static string WeightView_Label_DataBit {
            get {
                return ResourceManager.GetString("WeightView.Label.DataBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止位: 的本地化字符串。
        /// </summary>
        internal static string WeightView_Label_StopBit {
            get {
                return ResourceManager.GetString("WeightView.Label.StopBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子秤类型: 的本地化字符串。
        /// </summary>
        internal static string WeightView_Label_Type {
            get {
                return ResourceManager.GetString("WeightView.Label.Type", resourceCulture);
            }
        }
    }
}
