//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHS.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WHS.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 复制成功 的本地化字符串。
        /// </summary>
        public static string AboutView_CopyMessage {
            get {
                return ResourceManager.GetString("AboutView.CopyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬件ID： 的本地化字符串。
        /// </summary>
        public static string AboutView_Hardware {
            get {
                return ResourceManager.GetString("AboutView.Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string AboutView_HardwareButton {
            get {
                return ResourceManager.GetString("AboutView.HardwareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系 的本地化字符串。
        /// </summary>
        public static string AboutView_Tile_Contact {
            get {
                return ResourceManager.GetString("AboutView.Tile.Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string AboutView_Title {
            get {
                return ResourceManager.GetString("AboutView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        public static string FlyoutPluginManageView_Datagrid_Disable {
            get {
                return ResourceManager.GetString("FlyoutPluginManageView.Datagrid.Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string FlyoutPluginManageView_Datagrid_Enable {
            get {
                return ResourceManager.GetString("FlyoutPluginManageView.Datagrid.Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否显示 的本地化字符串。
        /// </summary>
        public static string FlyoutPluginManageView_Datagrid_IsDisplay {
            get {
                return ResourceManager.GetString("FlyoutPluginManageView.Datagrid.IsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制造商 的本地化字符串。
        /// </summary>
        public static string FlyoutPluginManageView_Datagrid_Manufacturer {
            get {
                return ResourceManager.GetString("FlyoutPluginManageView.Datagrid.Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string FlyoutPluginManageView_Datagrid_Name {
            get {
                return ResourceManager.GetString("FlyoutPluginManageView.Datagrid.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string FlyoutPluginManageView_Datagrid_OP {
            get {
                return ResourceManager.GetString("FlyoutPluginManageView.Datagrid.OP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号 的本地化字符串。
        /// </summary>
        public static string FlyoutPluginManageView_Datagrid_VersionString {
            get {
                return ResourceManager.GetString("FlyoutPluginManageView.Datagrid.VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程地址 的本地化字符串。
        /// </summary>
        public static string FlyoutWSConnectView_Datagrid_Address {
            get {
                return ResourceManager.GetString("FlyoutWSConnectView.Datagrid.Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string FlyoutWSConnectView_Datagrid_OP {
            get {
                return ResourceManager.GetString("FlyoutWSConnectView.Datagrid.OP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        public static string FlyoutWSConnectView_Datagrid_OP_REMOVE {
            get {
                return ResourceManager.GetString("FlyoutWSConnectView.Datagrid.OP_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志监控 的本地化字符串。
        /// </summary>
        public static string LogView_Content_Title {
            get {
                return ResourceManager.GetString("LogView.Content.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬件服务平台-欢迎光临 的本地化字符串。
        /// </summary>
        public static string MainWindow_Footer {
            get {
                return ResourceManager.GetString("MainWindow.Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言: 的本地化字符串。
        /// </summary>
        public static string MainWindow_Language {
            get {
                return ResourceManager.GetString("MainWindow.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓储硬件服务 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件管理 的本地化字符串。
        /// </summary>
        public static string PluginManage_Content_Title {
            get {
                return ResourceManager.GetString("PluginManage.Content.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WS连接监控 的本地化字符串。
        /// </summary>
        public static string WSConnectView_Content_Title {
            get {
                return ResourceManager.GetString("WSConnectView.Content.Title", resourceCulture);
            }
        }
    }
}
